-- return {
-- 	bundle_path = "~/Powershell/PowerShellEditorServices",
-- 	cmd = {
-- 		"pwsh",
-- 		"-NoLogo",
-- 		"-NoProfile",
-- 		"-Command",
-- 		"~/Powershell/PowerShellEditorServices/Start-EditorServices.ps1",
-- 	},
-- }
