require("noa.plugins.packer")
require("Comment").setup({})

require("noa.plugins.telescope")
require("noa.plugins.toggleterm")
require("noa.plugins.autopairs")
require("noa.plugins.completion")
require("noa.plugins.luasnip")
require("noa.plugins.treesitter")
require("noa.plugins.projects")
require("noa.plugins.filetree")
require("noa.plugins.surround")
require("noa.plugins.leap")
require("noa.plugins.alpha-nvim")
require("noa.plugins.theme")
require("noa.plugins.orgmode")
require("noa.plugins.undotree")
require("noa.plugins.firenvim")

require("trouble").setup({})
require("lsp-colors").setup()
require("nvim-web-devicons").setup({})
